# $Id$

COMMENT=	"monitors logfiles and performs commands"

DISTNAME=	logfmon-0.7
CATEGORIES=	security

MAINTAINER=     Nicholas Marriott <nicm__@ntlworld.com>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=logfmon/}

.include <bsd.port.mk>
