.\" $Id$
.\"
.\" Copyright (c) 2004 Nicholas Marriott <nicholas.marriott@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
.\" IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 8, 2004
.Dt LOGFMON 8
.Os
.Sh NAME
.Nm logfmon
.Nd "log file monitoring daemon"
.Sh SYNOPSIS
.Nm logfmon
.Bk -words
.Op Fl dsv
.Op Fl f Ar conffile
.Op Fl c Ar cachefile
.Op Fl p Ar pidfile
.Ek
.Sh DESCRIPTION
The
.Nm
daemon monitors a set of syslog log files and matches each new entry
against the rules defined in its configuration file. Each rule may be
tested against entries from a single file, a set of files or from all
files. Depending on the rule, a command may be executed or the entry
may be ignored. All unmatched messages are batched together and mailed
every 15 minutes, or whatever alternative time is specified in the
configuration file.
.Pp
Messages may also be collected into contexts and piped to a command
after a final message is found or a number of messages is reached. See
.Xr logfmon.conf 5
for more details of this.
.Pp
The options are as follows:
.Bl -tag -width "-f fileXXX"
.It Fl c Ar cachefile
Specify the cache file location. Default is
.Pa /var/db/logfmon.cache .
.Pp
This overrides any location specified in the configuration file.
.It Fl d
Run in the foreground and log to
.Em stderr .
.Pp
This option also causes additional debugging messages to be generated.
This option may be specified multiple times for increasing levels of verbosity.
.It Fl s
Monitor
.Em stdin .
This causes 
.Nm
to remain in the foreground and filter log messages passed on stdin.
.It Fl f Ar conffile
Specify the configuration file location. Default is
.Pa /etc/logfmon.conf .
.It Fl p Ar pidfile
Specify the pid file location. Default is
.Pa /var/run/logfmon.pid .
.Pp
This overrides any location specified in the configuration file.
.It Fl v
Display the
.Nm
version, and exit.
.El
.Sh FILES
.Bl -tag -width "/etc/logfmon.confXXX" -compact
.It Pa /etc/logfmon.conf
default
.Nm
configuration file
.El
.Sh SEE ALSO
.Xr syslog 3 ,
.Xr logfmon.conf 5
.Sh AUTHORS
.An Nicholas Marriott Aq nicholas.marriott@gmail.com
