#!/bin/bash

# source application-specific settings
LOGFMON_ARGS=
[ -f /etc/conf.d/logfmon ] && . /etc/conf.d/logfmon

. /etc/rc.conf
. /etc/rc.d/functions

PID=`cat /var/run/logfmon.pid 2>/dev/null`
case "$1" in
  start)
    stat_busy "Starting Log File Monitor"
    [ -z "$PID" ] && /usr/sbin/logfmon ${LOGFMON_ARGS}
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon logfmon
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Log File Monitor"
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon logfmon
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
