# $Id$

COMMENT=	"monitors logfiles and performs commands"

DISTNAME=	logfmon-0.8a
CATEGORIES=	security

MAINTAINER=     Nicholas Marriott <nicm@users.sourceforge.net>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB= c m pthread

MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=logfmon/}

.include <bsd.port.mk>
